version: '3'
services:
  app:
    image: flagr-test:latest
    build: .
    ports:
      - 3000:3000
    links:
      - flagr
    depends_on:
      - flagr
  flagr:
    image: checkr/flagr:latest
    environment:
      FLAGR_DB_DBDRIVER: postgres
      FLAGR_DB_DBCONNECTIONSTR: postgres://user:password@postgres:5432/flagr-test?sslmode=disable
    ports:
      - 18000:18000
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - 6000:5432
    environment:
      POSTGRES_DB: flagr-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - 'flagr-test:/var/lib/flagr-test/data'

volumes:
  flagr-test:
    driver: local
